### ISSUE TITLE
Code based "creative project" idea aggregator / collection

### ISSUE THREAD

**Issue by js6450** [Open-Source-Studio-at-ITP/Final-Projects#12]
This sounds really vague, but I have recently been thinking about how a lot of code-based works are very short lived. A lot of ITP-style projects tend to be short lived because libraries get updated, functions become deprecated, browser no longer supports this or that.

So, I've been thinking, what if we create a repository / website of our projects or ideas for projects in pseudo code form? Or not even in pseudo code, but in Sol Lewitt style of instructions? Also, it would be cool if we could let people comment / add links to their iteration / interpretation of the instruction. 

I don't really know what kind of form this would take actually. But I wanted to explore the idea of open source instructions, specifically for code based art.

**Comment by marcelmouse** [comment]
cool idea !

seen this? https://github.com/wholepixel/solving-sol

**Comment by linzhangcs** [comment]
Great idea! It would be really fun to see different interpretations of the same instruction.

**Comment by shiffman** [comment]
Interesting, this reminds me a bit of initiatives that compile algorithms and pseudo-code for those algorithms (so from a comp sci angle rather than creative project angle). Some recently shared a really nice one with me but I can't seem to find it with a google search right now. 

There is also [ReCode Project](http://recodeproject.com/) by ITP alum @matthewepler which relates to the idea in some ways.
