### ISSUE TITLE
ml5.js collaboration - Final Project

### ISSUE THREAD

**Issue by guillemontecinos** [Open-Source-Studio-at-ITP/Final-Projects#20]
# Pre-trained models
Some pre-trained models for style transfer -as *Matilde Pérez* and *Matta*- are not as accurate as expected. I'd like to improve them by checking the dataset built for training the model and correcting if needed. I'd like to train other models if there are any on demand.

# Learning material
I've realized that ml5.js learning material is pretty well documented. Apart from that there are tutorials in The Coding Train.
Despite, there are many things to do in order to make ML more accessible. I'd like to develop an intro tutorial more detailed, maybe as a proto-tiny-guide, inspired in the intro to p5.js book. If not, there is material still in a development stage, as the [pix2pix tutorial](https://ml5js.org/docs/pix2pix-example) that could be addressed.

# Code
I don't know if coding improves are needed in the project -probably there are- but I'd like to collaborate in them. I'll talk to Cristóbal about it.

**Comment by shiffman** [comment]
In general for a contribution within a fixed period of time, it's useful to map out a specific project with a deliverable rather than "general code / bug fixes". I think a tutorial for ml5 as well as contributing more pre-trained models are both projects that would be helpful. Re: pre-trained models, helping to curate diversity in what models we provide is particularly needed.
