### ISSUE TITLE
citizen journalism as open source investigation

### ISSUE THREAD

**Issue by marcelmouse** [Open-Source-Studio-at-ITP/Final-Projects#6]
Thinking about this project: https://www.bellingcat.com/

What _is_ open source investigation? Can anyone contribute? What is the github equivalent?

**Comment by lunaog** [comment]
omg I love that you posted this. citizen journalism is open source investigation, right?

It really reminds me of just fake news and the fact that in a way we are living in an era where all news is becoming more fake as the local / individual subjectivity becomes more blatant...but then there's a very real professionalism + standard that needs to be kept in order to uphold order.

**Comment by shiffman** [comment]
Yes, I agree that "citizen journalism" is a kind of open source that could absolutely be explored for a final project. @doodybrains can you re-title this post with something more specific than "Possible Final Project idea"?

**Comment by muji786** [comment]
i think this is a great idea to run on github... not only can anyone contribute, there's provenance of where the information is coming from, who is editing it and how... If information like this was available for all journalists, hidden biases and fake news would be easier to identify
